# Generated by Django 5.0 on 2023-12-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.category')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personEventCreater', to='users.profile')),
                ('users', models.ManyToManyField(blank=True, null=True, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.category')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamEventCreater', to='users.team')),
                ('teams', models.ManyToManyField(blank=True, null=True, related_name='TeamEventsTeams', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_profile', to='users.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_profile', to='users.profile')),
            ],
        ),
    ]
