# Generated by Django 5.0 on 2023-12-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=455)),
                ('address', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.category')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventAdmin', to='users.profile')),
                ('users', models.ManyToManyField(blank=True, null=True, to='users.profile')),
            ],
        ),
    ]
